use mysql;

CHANGE MASTER TO MASTER_HOST='172.18.0.2', MASTER_PORT=3306, MASTER_USER='admin', MASTER_PASSWORD='1234', MASTER_LOG_FILE='mysql-bin.000003', MASTER_LOG_POS=156;

-- CHANGE MASTER TO MASTER_HOST='mysql', MASTER_PORT=3306, MASTER_USER='admin', MASTER_PASSWORD='1234', MASTER_LOG_FILE='mysql-bin.000003', MASTER_LOG_POS=156, GET_MASTER_PUBLIC_KEY=1;

GRANT INSERT,SELECT,UPDATE,DELETE ON `db_test`.* TO `user`@`%`;