version: "3.8"

services:
  mysql-master:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: 'shopping'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '1234'
      
      
    ports:
      - '3307:3306'
    volumes:
      - master:/var/lib/mysql
      - master:/var/lib/mysql-files
    networks:
      - mysql-local-bridge

  mysql-slave:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: 'shopping'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '1234'
      
    ports:
      - '3308:3306'
    volumes:
      - slave:/var/lib/mysql
      - slave:/var/lib/mysql-files
    networks:
      - mysql-local-bridge

volumes:
  master:
  slave:

networks:
  mysql-local-bridge:
    driver: bridge